apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mi4r7qmz0-python
  janus-idp.io/tekton: mi4r7qmz0-python
  backstage.io/kubernetes-id: mi4r7qmz0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mi4r7qmz0-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
